# Generated by Django 3.2.4 on 2021-06-05 15:26

from django.db import migrations, models
import django.db.models.deletion
import tutorial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order_num', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=tutorial.models.theme_avatar_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(upload_to=tutorial.models.task_avatar_directory_path)),
                ('hints', models.TextField()),
                ('author_solution', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.theme')),
            ],
        ),
    ]
