# Generated by Django 3.2.4 on 2021-06-05 17:24

from django.db import migrations, models
import tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='task',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tutorial.models.task_avatar_directory_path),
        ),
    ]
