# Generated by Django 3.2.4 on 2021-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20210605_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
