# Generated by Django 3.2.4 on 2021-07-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
