# Generated by Django 3.2.4 on 2021-07-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_task_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='withfile',
            field=models.IntegerField(default=0),
        ),
    ]
