# Generated by Django 3.2.4 on 2021-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_task_withfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='withtest',
            field=models.IntegerField(default=1),
        ),
    ]
