# Generated by Django 3.2.4 on 2021-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_task_withtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='withimg',
            field=models.IntegerField(default=0),
        ),
    ]
