# Generated by Django 3.2.4 on 2021-07-28 12:53

from django.db import migrations, models
import tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_task_withimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_file',
            field=models.FileField(blank=True, upload_to=tutorial.models.task_testfile_directory_path),
        ),
    ]
