# Generated by Django 3.2.4 on 2021-07-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_task_test_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hints',
            new_name='hint',
        ),
    ]
