# Generated by Django 3.2.4 on 2021-07-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_rename_hints_task_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
