# Generated by Django 3.2.4 on 2021-07-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_alter_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title_url',
        ),
    ]
