# Generated by Django 3.2.4 on 2021-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_remove_task_title_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='default_code',
            field=models.TextField(default=''),
        ),
    ]
