# Generated by Django 3.2.4 on 2021-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_auto_20210805_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Юзер и решение', 'verbose_name_plural': 'Юзера и решения'},
        ),
    ]
