# Generated by Django 3.2.4 on 2021-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0017_alter_trick_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
