# Generated by Django 3.2.4 on 2021-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0020_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile', models.ManyToManyField(blank=True, to='tutorial.Profile')),
                ('theme', models.ManyToManyField(blank=True, to='tutorial.Theme')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
