# Generated by Django 3.2.4 on 2021-11-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0022_auto_20211119_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avatar',
        ),
    ]
