# Generated by Django 3.2.4 on 2021-11-19 18:13

from django.db import migrations, models
import tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_remove_course_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tutorial.models.course_avatar_directory_path),
        ),
    ]
