# Generated by Django 3.2.4 on 2021-11-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_course_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='task',
            field=models.ManyToManyField(blank=True, to='tutorial.Task'),
        ),
    ]
