# Generated by Django 3.2.4 on 2021-11-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0025_course_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avatar',
        ),
    ]
