# Generated by Django 3.2.4 on 2021-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0026_remove_course_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
