# Generated by Django 3.2.4 on 2021-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0027_course_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='finish',
            field=models.DateTimeField(default='2000-01-01T00:00:00+00:00'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='first_view',
            field=models.DateTimeField(default='2000-01-01T00:00:00+00:00'),
        ),
    ]
