# Generated by Django 3.2.4 on 2021-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0029_auto_20211126_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='attemptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
