# Generated by Django 3.2.4 on 2021-12-01 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0030_auto_20211130_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='first_view',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
